// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7NdZHjdfYNUPq5aHo933N03pIcEYM0yo',
    appId: '1:412358666396:web:6011b43231e4b320b8a559',
    messagingSenderId: '412358666396',
    projectId: 'ehealthsolution-8e2b6',
    authDomain: 'ehealthsolution-8e2b6.firebaseapp.com',
    databaseURL: 'https://ehealthsolution-8e2b6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ehealthsolution-8e2b6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7pX5OZNG2DAjhhOAPbqn5HHbxkVm4a_M',
    appId: '1:412358666396:android:154f461d7160c02fb8a559',
    messagingSenderId: '412358666396',
    projectId: 'ehealthsolution-8e2b6',
    databaseURL: 'https://ehealthsolution-8e2b6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ehealthsolution-8e2b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBdrPI77R1OAWC3i3hH4DGzDRLiLHMO0M',
    appId: '1:412358666396:ios:59d3b48af1e4bd7cb8a559',
    messagingSenderId: '412358666396',
    projectId: 'ehealthsolution-8e2b6',
    databaseURL: 'https://ehealthsolution-8e2b6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ehealthsolution-8e2b6.firebasestorage.app',
    androidClientId: '412358666396-mifhr0p1b1hqs21b6lei7t7ai47im3vm.apps.googleusercontent.com',
    iosClientId: '412358666396-b4bg50e77dc33b2f5ioufjef1fjfma7s.apps.googleusercontent.com',
    iosBundleId: 'com.example.ehealthsolution',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBdrPI77R1OAWC3i3hH4DGzDRLiLHMO0M',
    appId: '1:412358666396:ios:59d3b48af1e4bd7cb8a559',
    messagingSenderId: '412358666396',
    projectId: 'ehealthsolution-8e2b6',
    databaseURL: 'https://ehealthsolution-8e2b6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ehealthsolution-8e2b6.firebasestorage.app',
    androidClientId: '412358666396-mifhr0p1b1hqs21b6lei7t7ai47im3vm.apps.googleusercontent.com',
    iosClientId: '412358666396-b4bg50e77dc33b2f5ioufjef1fjfma7s.apps.googleusercontent.com',
    iosBundleId: 'com.example.ehealthsolution',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7NdZHjdfYNUPq5aHo933N03pIcEYM0yo',
    appId: '1:412358666396:web:504fd15f9cc7353ab8a559',
    messagingSenderId: '412358666396',
    projectId: 'ehealthsolution-8e2b6',
    authDomain: 'ehealthsolution-8e2b6.firebaseapp.com',
    databaseURL: 'https://ehealthsolution-8e2b6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ehealthsolution-8e2b6.firebasestorage.app',
  );
}
